####
## Gramedia Digital - Data Engineer Take Home Test
## by Mario Caesar // caesarmario87@gmail.com
## Yaml config to be used in jinja template for DAG scripts
####

project: fakestore
base_url: https://fakestoreapi.com
resources:
  - name: products
    endpoint: /products
  - name: carts
    endpoint: /carts
  - name: users
    endpoint: /users
